### ISSUE TITLE
Enhancement suggestion for OSPi152.stl

### ISSUE THREAD

**Issue by daz10000** [OpenSprinkler/OpenSprinkler-Hardware#10]
Small suggestion but making a perforation or opening for the ethernet port would be handy - I guess people just deploy these things on wifi, but if you want to do a wired connection you need a drill :) - I should have thought of this before printing and just made a hole - my bad.
![IMG_3947](https://user-images.githubusercontent.com/6342645/199127311-1f97c044-45eb-477e-bd0b-6a61fabe6e4b.jpg)

**Comment by Sputnick85** [comment]
It would be great to have access to the USB Ports as well :)

**Comment by rayshobby** [comment]
I will have to leave this for the user to modify the 3D model themselves. Different RPis may have different ports and positions (for example, the USB and Ethernet jack on RPi 4 and RPi 5 are not the same). Since I don't own all versions of RPis, I won't be able to create one variant for each RPi.
