### ISSUE TITLE
v1.6 missing?

### ISSUE THREAD

**Issue by themikem** [OpenSprinkler/OpenSprinkler-Hardware#12]
Hi,

I recently purchased an OpenSprinkler Pi board which is labeled as v1.60. However I don’t see the v1.60 schematics in this repo.

I’m trying to determine how to disconnect the voltage regulator that feeds the pi, as when both the USB-C and 24v ac connectors are attached, the Pi will not boot. (Using a pi 5)

is there somewhere else I should look for a newer version? Having a matching schematic would be a big help at the moment.

Thanks!

**Comment by rayshobby** [comment]
I've just added v1.60 design files. The main difference is v1.6 has changed the ADC chip from the previous PCF8591 (obsolete part) to ADS1115. That said, the OpenSprinkler firmware doesn't support OSPi ADC at the moment yet, so this change is really only meant for the future when ADS support will be added.

I am a bit surprised that your RPi can't boot when having both USB-C and 24V connected. Generally this should work just fine. If you want to disconnect OSPi's 5V to RPi, there are a few possible approaches:

1. On the OSPi board, cut the +5V trace that goes to the two +5V pins on the 2x20 female pin header (this trace is on the back of the board). 
2. If you'd rather not cut the trace, here is another way: at the 24VAC orange terminal block, the top pin is GND, the bottom pin is 24VAC. Remove the bottom pin from the orange terminal block, also remove the common wire from the COM terminal, then directly connect these two wires together (i.e. the original 24VAC wire goes straight to common wire without any terminal block). This way, the OSPi board won't be powered from 24VAC, but 24VAC will still be used to power the solenoids.
