### ISSUE TITLE
Here are the Gerber for hardware v3.1

### ISSUE THREAD

**Issue by laurentopia** [OpenSprinkler/OpenSprinkler-Hardware#3]
[os31_master_2018-08-24.zip](https://github.com/OpenSprinkler/OpenSprinkler-Hardware/files/2319473/os31_master_2018-08-24.zip)
[dcdr_3.1_2018-08-24.zip](https://github.com/OpenSprinkler/OpenSprinkler-Hardware/files/2319474/dcdr_3.1_2018-08-24.zip)
[exp31dc_2018-08-24.zip](https://github.com/OpenSprinkler/OpenSprinkler-Hardware/files/2319475/exp31dc_2018-08-24.zip)

**Comment by Egyras** [comment]
@laurentopia maybe have ac version ?

**Comment by rayshobby** [comment]
there is no need to upload gerber files -- if you install EagleCAD software, you can open any opensprinkler hardware design files (.sch and .brd) and export gerber youself.
