### ISSUE TITLE
C2 not connected in Acdr_3.2.brd 

### ISSUE THREAD

**Issue by DarioB92** [OpenSprinkler/OpenSprinkler-Hardware#5]
Not sure if it's a mine issue, but C2 doesn't looks connected.
![image](https://user-images.githubusercontent.com/39674389/88939483-db9a6200-d286-11ea-9c4e-05085fe73e38.png)![image](https://user-images.githubusercontent.com/39674389/88939718-25834800-d287-11ea-8944-c687fdbc7668.png)

**Comment by Egyras** [comment]
@DarioB92 I have double checked with latest Eagle its same issue... Seems its missing connection to DGND net.
@rayshobby can it be fixed ? Thanks!

**Comment by rayshobby** [comment]
This has been fixed in the updated version. Please check the corresponding folder.
