### ISSUE TITLE
Can't open .brd or .sch files

### ISSUE THREAD

**Issue by martinpala** [OpenSprinkler/OpenSprinkler-Hardware#7]
Using EAGLE 9.6.2. education
Error when opening dcdr_3.2.brd
Error when opening other files as well
errorcode:
line 8, column 16: This is not an EAGLE file.

Thanks.

**Comment by DKCroCo** [comment]
I have the same issue.

**Comment by WhiteCarcosa** [comment]
> I have the same issue.

You may need be altering the file during the save process like i was. Right clicking the RAW button and saving fixed the issue for me.

**Comment by rayshobby** [comment]
I just tried opening these files in Eagle 9.6.2. They opened just fine. No problem with them. You can try to download the entire repository and unzip it, instead of downloading a single file.
